### ISSUE TITLE
Missing yaml dependency

### ISSUE THREAD

**Issue by rbardenet** [guillep/python-grocery-list#2]
My configuration :
- OSX El Capitan
- Python 2.7

@guillep hey @guilgautier, what's up?

After cloning the repo, I tried to run `python2.7 grocery-list.py`, but got 
```
Traceback (most recent call last):
  File "grocery-list.py", line 2, in <module>
    import yaml
ImportError: No module named yaml
```

**Comment by CameronHurdle** [comment]
im lost as to what to do the yaml says its no modules and i dont see where you guys fixed it because the new text file requirements is empty

**Comment by guillep** [comment]
Hi,

To load the pyyaml dependency, there are several options. Either it is done manually using `pip install ...` or you can enforce the dependencies specified in the `setup.py` like

```
$ sudo python setup.py install
```

After this, I was able to execute the grocery list.

I'll  update the README file with this information.
Remember however that this is an example project to learn ^^.
